server:
  port: 8080
spring:
  jpa:
      database: MYSQL
      hibernate:
            ddl-auto: update

  datasource:
        url: jdbc:mysql://localhost:3306/cat_1
        username: root
        password: 1nd[mbu
        driver-class-name: com.mysql.jdbc.Driver